# Generated by Django 5.2.6 on 2025-10-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_category_regularorder_product_regularorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='design_upload',
            field=models.FileField(blank=True, help_text='Upload your design (.pdf, .jpeg, .png)', null=True, upload_to='custom_designs/'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='fabric_type',
            field=models.CharField(choices=[('cotton', '100% Cotton'), ('polyester', '100% Polyester'), ('blend', 'Cotton-Polyester Blend'), ('organic_cotton', 'Organic Cotton'), ('bamboo', 'Bamboo Fabric'), ('linen', 'Linen'), ('fleece', 'Fleece'), ('jersey', 'Jersey Knit')], default='cotton', max_length=20),
        ),
        migrations.AddField(
            model_name='customorder',
            name='price_range',
            field=models.CharField(choices=[('budget', '$20 - $30 (Budget Friendly)'), ('standard', '$30 - $50 (Standard Quality)'), ('premium', '$50 - $75 (Premium Quality)'), ('luxury', '$75+ (Luxury/Designer)')], default='standard', max_length=20),
        ),
    ]
