# Generated by Django 5.2.6 on 2025-10-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customorder_design_upload_customorder_fabric_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Design image/preview', upload_to='designs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='designs/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customorder',
            name='design_placement',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both Front & Back')], default='front', help_text='Where to place the design', max_length=10),
        ),
        migrations.AddField(
            model_name='customorder',
            name='selected_design',
            field=models.ForeignKey(blank=True, help_text='Pre-made design selected by customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_orders', to='shop.design'),
        ),
    ]
