# Generated by Django 5.2.6 on 2025-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_design_customorder_design_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customorder',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customorder',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI (PhonePe, Google Pay, Paytm)'), ('net_banking', 'Net Banking'), ('paypal', 'PayPal'), ('google_pay', 'Google Pay'), ('paytm', 'Paytm Wallet'), ('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regularorderpayment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI (PhonePe, Google Pay, Paytm)'), ('net_banking', 'Net Banking'), ('paypal', 'PayPal'), ('google_pay', 'Google Pay'), ('paytm', 'Paytm Wallet'), ('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regularordershipping',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
