# Generated by Django 5.2.16 on 2026-08-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_add_otp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='price_range',
            field=models.CharField(choices=[('budget', '₹800 - ₹1200 (Budget Friendly)'), ('standard', '₹1200 - ₹2000 (Standard Quality)'), ('premium', '₹2000 - ₹3000 (Premium Quality)'), ('luxury', '₹3000+ (Luxury/Designer)')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
    ]
